language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - 4
  - 5
  - 6
  - 7
services:
  - mongodb
after_install:
  - npm install codacy-coverage
script:
  - npm run lint
  - npm run test:coverage
after_script:
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
